// front-end/src/pages/login/Login.tsx
import { Card, Row, Typography, Form, Button, Input } from "antd";
const { Title } = Typography;
const Login = () => {
  const onFinish = (data: any) => {
    console.log(data);
  };
  const onFinishFailed = () => {};
  return (
    <Row justify="center" align="middle" style={{ minHeight: "100vh" }}>
      <Card>
        <Title style={{ textAlign: "center" }}>Login</Title>
        <Form
          name="basic"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          initialValues={{ remember: true }}
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          autoComplete="off"
        >
          <Form.Item
            label="Username"
            name="username"
            rules={[{ required: true, message: "Please input your username!" }]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Password"
            name="password"
            rules={[{ required: true, message: "Please input your password!" }]}
          >
            <Input.Password />
          </Form.Item>

          <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
            <Button type="primary" htmlType="submit">
              Submit
            </Button>
          </Form.Item>
        </Form>
      </Card>
    </Row>
  );
};
export default Login;

// front-end/pages/admin/login/index.vue
<template>
  <div class="h-100">
    <b-row
      class="justify-content-center align-items-center text-center min-vh-100"
    >
      <b-col cols="4">
        <b-card>
          <b-form @submit.prevent="userLogin">
            <b-form-group label="Username">
              <b-form-input type="text" v-model="login.username"></b-form-input>
            </b-form-group>
            <b-form-group label="Password">
              <b-form-input
                type="password"
                v-model="login.password"
              ></b-form-input>
            </b-form-group>
            <b-button type="submit" block>Login</b-button>
          </b-form>
        </b-card>
      </b-col>
    </b-row>
  </div>
</template>
<script>
export default {
  layout: "login",
  auth: false,
  data() {
    return {
      login: {
        useruser: "",
        password: "",
      },
    };
  },
  methods: {
    async userLogin() {
      try {
        await this.$auth.loginWith('local', { data: this.login });
        console.log(this.$auth.user)
      } catch (err) {
        console.log(err)
      }
    }
  }
};
</script>
